mti_le_bon_coin:
    resource: "@MTILeBonCoinBundle/Resources/config/routing.yml"
    prefix:   /

mti_user_back_office:
    resource: "@MTIUserBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

mti_home:
    resource: "@MTIApiProjectHomeBundle/Resources/config/routing.yml"
    prefix:   /

mti_hello_world:
    resource: "@MTIHelloWorldBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    pattern:   /
    defaults:  { _controller: MTIApiProjectHomeBundle:Home:index }